# Generated by Django 4.2.21 on 2025-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
