# Generated by Django 4.2.21 on 2025-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_orderitem_packed_alter_bakesaleperiod_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
